# Case No 1 : Perceptron Model

In [1]:
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
  'pixel_5_2',
  'pixel_5_3',
  'pixel_5_4',
  'pixel_5_5',
  'pixel_5_6',
  'pixel_5_7',
  'pixel_6_0',
  'pixel_6_1',
  'pixel_6_2',
  'pixel_6_3',
  'pixel_6_4',
  'pixel_6_5',
  'pixel_6_6',
  'pixel_6_7',
  'pixel_7_0',
  'pixel_7_1',
  'pixel_7_2',
  'pixel_7_3',
  'pixel_7_4',
  'pixel_7_5',
  'pixel_7_6',
  'pixel_7_7'],
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

        [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
         [ 0.,  0.,  3., ..., 14.,  0.,  0.],
         [ 0.,  0.,  8., ..., 16.,  0.,  0.],
         ...,
         [ 0.,  9., 16., ...,  0.,  0.,  0.],
         [ 0.,  3., 13., ..., 11.,  5.,  0.],
         [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

        ...,

        [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ...,  2.,  1.,  0.],
         [ 0.,  0., 16., ..., 16.,  5.,  0.],
         ...,
         [ 0.,  0., 16., ..., 15.,  0.,  0.],
         [ 0.,  0., 15., ..., 16.,  0.,  0.],
         [ 0.,  0.,  2., ...,  6.,  0.,  0.]],

        [[ 0.,  0.,  2., ...,  0.,  0.,  0.],
         [ 0.,  0., 14., ..., 15.,  1.,  0.],
         [ 0.,  4., 16., ..., 16.,  7.,  0.],
         ...,
         [ 0.,  0.,  0., ..., 16.,  2.,  0.],
         [ 0.,  0.,  4., ..., 16.,  2.,  0.],
         [ 0.,  0.,  5., ..., 12.,  0.,  0.]],

        [[ 0.,  0., 10., ...,  1.,  0.,  0.],
         [ 0.,  2., 16., ...,  1.,  0.,  0.],
         [ 0.,  0., 15., ..., 15.,  0.,  0.],
         ...,
         [ 0.,  4., 16., ..., 16.,  6.,  0.],
         [ 0.,  8., 16., ..., 16.,  8.,  0.],
         [ 0.,  1.,  8., ..., 12.,  1.,  0.]]]),
 'DESCR': ".. _digits_dataset:\n\nOptical recognition of handwritten digits dataset\n--------------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 1797\n    :Number of Attributes: 64\n    :Attribute Information: 8x8 image of integer pixels in the range 0..16.\n    :Missing Attribute Values: None\n    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)\n    :Date: July; 1998\n\nThis is a copy of the test set of the UCI ML hand-written digits datasets\nhttps://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits\n\nThe data set contains images of hand-written digits: 10 classes where\neach class refers to a digit.\n\nPreprocessing programs made available by NIST were used to extract\nnormalized bitmaps of handwritten digits from a preprinted form. From a\ntotal of 43 people, 30 contributed to the training set and different 13\nto the test set. 32x32 bitmaps are divided into nonoverlapping blocks of\n4x4 and the number of on pixels are counted in each block. This generates\nan input matrix of 8x8 where each element is an integer in the range\n0..16. This reduces dimensionality and gives invariance to small\ndistortions.\n\nFor info on NIST preprocessing routines, see M. D. Garris, J. L. Blue, G.\nT. Candela, D. L. Dimmick, J. Geist, P. J. Grother, S. A. Janet, and C.\nL. Wilson, NIST Form-Based Handprint Recognition System, NISTIR 5469,\n1994.\n\n.. topic:: References\n\n  - C. Kaynak (1995) Methods of Combining Multiple Classifiers and Their\n    Applications to Handwritten Digit Recognition, MSc Thesis, Institute of\n    Graduate Studies in Science and Engineering, Bogazici University.\n  - E. Alpaydin, C. Kaynak (1998) Cascading Classifiers, Kybernetika.\n  - Ken Tang and Ponnuthurai N. Suganthan and Xi Yao and A. Kai Qin.\n    Linear dimensionalityreduction using relevance weighted LDA. School of\n    Electrical and Electronic Engineering Nanyang Technological University.\n    2005.\n  - Claudio Gentile. A New Approximate Maximal Margin Classification\n    Algorithm. NIPS. 2000.\n"}

In [3]:
digits['data']

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [4]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.linear_model import Perceptron

In [6]:
x = digits.data
y = digits.target

In [9]:
pd.DataFrame(x).shape

(1797, 64)

In [11]:
pd.DataFrame(y).value_counts()

3    183
1    182
5    182
4    181
6    181
9    180
7    179
0    178
2    177
8    174
Name: count, dtype: int64

In [12]:
pd.DataFrame(y).nunique()

0    10
dtype: int64

In [8]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [14]:
# Building perceptron model
pp = Perceptron()
pp.fit(x_train, y_train)
print("What is the Testing Accuracy")
print(pp.score(x_test, y_test))

What is the Testing Accuracy
0.9527777777777777

In [15]:
print("What is the Training Accuracy")
print(pp.score(x_train, y_train))

What is the Training Accuracy
0.9714683368128044

In [16]:
predicted = pp.predict(x_test)

In [17]:
print('\n confusion_matrix')
print(confusion_matrix(y_test, predicted))

 confusion_matrix
[[32  0  0  0  1  0  0  0  0  0]
 [ 0 28  0  0  0  0  0  0  0  0]
 [ 0  0 33  0  0  0  0  0  0  0]
 [ 0  0  1 31  0  1  0  0  1  0]
 [ 0  0  0  0 46  0  0  0  0  0]
 [ 0  0  1  0  0 45  1  0  0  0]
 [ 0  0  0  0  0  1 34  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  2  0  0  2  1  0  0 25  0]
 [ 0  0  0  0  1  1  0  0  2 36]]

In [18]:
print('\n classification_report')
print(classification_report(y_test, predicted))

 classification_report
              precision    recall  f1-score   support

           0       1.00      0.97      0.98        33
           1       0.93      1.00      0.97        28
           2       0.94      1.00      0.97        33
           3       1.00      0.91      0.95        34
           4       0.92      1.00      0.96        46
           5       0.92      0.96      0.94        47
           6       0.97      0.97      0.97        35
           7       1.00      0.97      0.99        34
           8       0.89      0.83      0.86        30
           9       0.97      0.90      0.94        40

    accuracy                           0.95       360
   macro avg       0.96      0.95      0.95       360
weighted avg       0.95      0.95      0.95       360

# Case number 2 : MultiLayer Perceptron Model - Regression Problem

In [19]:
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.16.1'

In [20]:
dataset = pd.read_csv('HousingData.csv')
dataset.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2

In [21]:
dataset.isnull().sum()

CRIM       20
ZN         20
INDUS      20
CHAS       20
NOX         0
RM          0
AGE        20
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT      20
MEDV        0
dtype: int64

In [23]:
# Handling missing value by using KNN imputation 
from sklearn.impute import KNNImputer

In [24]:
imputer = KNNImputer()
dataset1 = pd.DataFrame(imputer.fit_transform(dataset), columns = dataset.columns)

In [25]:
dataset1.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [26]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB

In [27]:
x = dataset1.iloc[:,:-1]
y = dataset1.iloc[:,-1]

In [28]:
x

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.20,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.90,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.10,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.80,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.20,6.0622,3.0,222.0,18.7,396.90,7.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.10,2.4786,1.0,273.0,21.0,391.99,9.38
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.70,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.00,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.30,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,78.86,2.5050,1.0,273.0,21.0,396.90,7.88

In [29]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [30]:
# Feature Scaling - Mandatory step
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_x = pd.DataFrame(scaler.fit_transform(x), columns=x.columns)
scaled_x

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,-0.425438,0.287980,-1.291623,-0.280228,-0.144217,0.413672,-0.125945,0.140214,-0.982843,-0.666608,-1.459000,0.441052,-1.085232
1,-0.423028,-0.488492,-0.595127,-0.280228,-0.740262,0.194274,0.368604,0.557160,-0.867883,-0.987329,-0.303094,0.441052,-0.498835
2,-0.423030,-0.488492,-0.595127,-0.280228,-0.740262,1.282714,-0.273949,0.557160,-0.867883,-0.987329,-0.303094,0.396427,-1.219144
3,-0.422447,-0.488492,-1.310645,-0.280228,-0.835284,1.016303,-0.826256,1.077737,-0.752922,-1.106115,0.113032,0.416163,-1.372791
4,-0.418235,-0.488492,-1.310645,-0.280228,-0.835284,1.228577,-0.523029,1.077737,-0.752922,-1.106115,0.113032,0.441052,-0.721553
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,-0.418972,-0.488492,0.116000,-0.280228,0.158124,0.439316,0.014839,-0.625796,-0.982843,-0.803212,1.176466,0.387217,-0.465005
502,-0.420966,-0.488492,0.116000,-0.280228,0.158124,-0.234548,0.289187,-0.716639,-0.982843,-0.803212,1.176466,0.441052,-0.507293
503,-0.419187,-0.488492,0.116000,-0.280228,0.158124,0.984960,0.805396,-0.773684,-0.982843,-0.803212,1.176466,0.441052,-0.992198
504,-0.413580,-0.488492,0.116000,-0.280228,0.158124,0.725672,0.744028,-0.668437,-0.982843,-0.803212,1.176466,0.403225,-0.873791
505,-0.420720,-0.488492,0.116000,-0.280228,0.158124,-0.362767,0.367160,-0.613246,-0.982843,-0.803212,1.176466,0.441052,-0.676446

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(scaled_x, y, test_size=0.25, random_state=42)

# MultiLayer Perceptron Model - Regression

In [33]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [34]:
# Initialize the Sequential model
model = Sequential()
# First fully connected Hidden Layer 
model.add(Dense(32, activation='relu', input_dim=13))
# Second fully connected Hidden Layer 
model.add(Dense(16, activation='relu'))
# output
model.add(Dense(1, activation='linear'))
model.summary()

C:\Users\KUMAR SUNDRAM\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                  │             448 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 993 (3.88 KB)

 Trainable params: 993 (3.88 KB)

 Non-trainable params: 0 (0.00 B)

In [35]:
13*32+32

448

In [36]:
32*16+16

528

In [37]:
x_train.shape

(379, 13)

In [38]:
379/32

11.84375

In [41]:
12*31

372

In [42]:
model.compile(optimizer='adam', loss='mse')
history = model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=100, batch_size=32)
# Gradient Descent optimization (BGD, SGD, MBGD)

Epoch 1/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 647.1906 - val_loss: 520.9471
Epoch 2/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 592.2048 - val_loss: 501.9973
Epoch 3/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 568.7278 - val_loss: 482.0432
Epoch 4/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 554.9806 - val_loss: 457.7381
Epoch 5/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 536.5605 - val_loss: 427.5407
Epoch 6/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 518.9854 - val_loss: 391.9147
Epoch 7/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 412.7351 - val_loss: 351.1270
Epoch 8/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 389.4438 - val_loss: 304.5561
Epoch 9/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 340.9988 - val_loss: 255.5328
Epoch 10/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 297.6331 - val_loss: 205.9433
Epoch 11/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 230.0863 - val_loss: 160.3469
Epoch 12/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 189.4417 - val_loss: 122.9066
Epoch 13/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 140.3813 - val_loss: 95.3031
Epoch 14/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 132.1243 - val_loss: 76.6152
Epoch 15/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 82.8834 - val_loss: 64.8734
Epoch 16/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 79.2151 - val_loss: 56.1879
Epoch 17/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 61.3523 - val_loss: 49.4558
Epoch 18/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 64.9440 - val_loss: 43.8258
Epoch 19/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 45.9545 - val_loss: 39.5264
Epoch 20/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 39.5476 - val_loss: 36.2053
Epoch 21/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 36.6515 - val_loss: 33.3946
Epoch 22/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 38.6542 - val_loss: 30.9807
Epoch 23/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 29.9572 - val_loss: 29.3169
Epoch 24/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 35.1653 - val_loss: 27.9237
Epoch 25/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 27.3447 - val_loss: 26.8791
Epoch 26/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 37.3088 - val_loss: 25.9226
Epoch 27/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 22.8883 - val_loss: 25.3728
Epoch 28/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 28.1548 - val_loss: 24.6395
Epoch 29/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 28.3200 - val_loss: 24.1749
Epoch 30/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22.7563 - val_loss: 23.7132
Epoch 31/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.9656 - val_loss: 23.1855
Epoch 32/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25.2636 - val_loss: 22.8825
Epoch 33/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 23.7192 - val_loss: 22.5354
Epoch 34/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.6831 - val_loss: 22.2752
Epoch 35/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.2318 - val_loss: 21.9686
Epoch 36/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 23.4361 - val_loss: 21.6565
Epoch 37/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 22.6468 - val_loss: 21.3848
Epoch 38/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.5948 - val_loss: 21.1887
Epoch 39/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 19.9326 - val_loss: 20.9653
Epoch 40/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.8376 - val_loss: 20.6950
Epoch 41/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 17.8646 - val_loss: 20.4921
Epoch 42/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 19.5700 - val_loss: 20.3239
Epoch 43/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 22.4317 - val_loss: 20.1167
Epoch 44/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 19.4301 - val_loss: 19.8622
Epoch 45/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 18.2164 - val_loss: 19.6089
Epoch 46/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.2764 - val_loss: 19.4137
Epoch 47/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 18.9102 - val_loss: 19.3020
Epoch 48/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.9968 - val_loss: 19.1326
Epoch 49/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.2358 - val_loss: 19.0087
Epoch 50/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 18.5063 - val_loss: 18.8089
Epoch 51/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 15.2533 - val_loss: 18.6262
Epoch 52/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.8029 - val_loss: 18.4462
Epoch 53/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.1150 - val_loss: 18.2533
Epoch 54/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.3944 - val_loss: 18.0306
Epoch 55/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 17.5400 - val_loss: 17.9587
Epoch 56/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.6638 - val_loss: 17.7853
Epoch 57/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.1783 - val_loss: 17.6415
Epoch 58/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.9843 - val_loss: 17.5552
Epoch 59/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 13.5254 - val_loss: 17.4019
Epoch 60/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.6059 - val_loss: 17.2037
Epoch 61/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.6693 - val_loss: 17.0617
Epoch 62/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.8032 - val_loss: 16.9533
Epoch 63/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.4382 - val_loss: 16.8890
Epoch 64/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.5036 - val_loss: 16.6920
Epoch 65/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15.2462 - val_loss: 16.5568
Epoch 66/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16.0468 - val_loss: 16.4807
Epoch 67/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 15.4398 - val_loss: 16.4425
Epoch 68/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.8085 - val_loss: 16.3305
Epoch 69/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.9775 - val_loss: 16.2792
Epoch 70/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.4637 - val_loss: 16.2108
Epoch 71/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15.1399 - val_loss: 15.9962
Epoch 72/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.8836 - val_loss: 15.8933
Epoch 73/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.7895 - val_loss: 15.8448
Epoch 74/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.4254 - val_loss: 15.7534
Epoch 75/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.8193 - val_loss: 15.6802
Epoch 76/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.8556 - val_loss: 15.5656
Epoch 77/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.9053 - val_loss: 15.4603
Epoch 78/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 17.2208 - val_loss: 15.3445
Epoch 79/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.3283 - val_loss: 15.3090
Epoch 80/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 14.0412 - val_loss: 15.3121
Epoch 81/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.6228 - val_loss: 15.1945
Epoch 82/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.9511 - val_loss: 15.1279
Epoch 83/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.8122 - val_loss: 15.0399
Epoch 84/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.2578 - val_loss: 14.8931
Epoch 85/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.0528 - val_loss: 14.8149
Epoch 86/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.1073 - val_loss: 14.8190
Epoch 87/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.1304 - val_loss: 14.8054
Epoch 88/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.9814 - val_loss: 14.6252
Epoch 89/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.6327 - val_loss: 14.5654
Epoch 90/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12.9189 - val_loss: 14.5373
Epoch 91/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.9469 - val_loss: 14.4602
Epoch 92/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.0966 - val_loss: 14.4033
Epoch 93/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11.4481 - val_loss: 14.2542
Epoch 94/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.6635 - val_loss: 14.2606
Epoch 95/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12.5856 - val_loss: 14.1967
Epoch 96/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.2829 - val_loss: 14.1360
Epoch 97/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.2463 - val_loss: 14.0710
Epoch 98/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.4790 - val_loss: 13.9685
Epoch 99/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.0554 - val_loss: 13.9584
Epoch 100/100
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.5612 - val_loss: 13.8784

In [43]:
new_data = pd.read_csv('HousingData_test.csv')
new_data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Unnamed: 13
0,0.009,13,3,1,0.9,7,50,3.9,1,325,17,450,6,NaN
1,0.090,14,5,0,0.8,8,65,6.0,2,400,16,430,7,NaN
2,0.070,17,6,1,0.7,9,54,8.0,2,400,19,288,8,NaN

In [44]:
new_data = new_data.iloc[:,:-1]
new_data

    CRIM  ZN  INDUS  CHAS  NOX  RM  AGE  DIS  RAD  TAX  PTRATIO    B  LSTAT
0  0.009  13      3     1  0.9   7   50  3.9    1  325       17  450      6
1  0.090  14      5     0  0.8   8   65  6.0    2  400       16  430      7
2  0.070  17      6     1  0.7   9   54  8.0    2  400       19  288      8

In [45]:
new_data.shape

(3, 13)

In [46]:
scaled_new_data = pd.DataFrame(scaler.transform(new_data), columns=new_data.columns)
scaled_new_data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,-0.425130,0.072293,-1.190660,3.702785,2.982858,1.019152,-0.674642,0.049893,-0.982843,-0.494369,-0.672984,1.023259,-0.941452
1,-0.415830,0.115431,-0.898015,-0.280228,2.119025,2.443811,-0.133165,1.048169,-0.867883,-0.048923,-1.135347,0.803972,-0.800491
2,-0.418126,0.244843,-0.751693,3.702785,1.255192,3.868469,-0.530248,1.998907,-0.867883,-0.048923,0.251741,-0.752967,-0.659530

In [47]:
y_pred = model.predict(scaled_new_data)
print(y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
[[23.824772]
 [31.382582]
 [31.826935]]

In [48]:
# RandomForestRegressor

In [49]:
from sklearn.ensemble import RandomForestRegressor

In [50]:
rforest = RandomForestRegressor()
rforest.fit(x_train, y_train)

RandomForestRegressor()

In [58]:
y_pred_test = rforest.predict(x_test)
y_pred_train = rforest.predict(x_train)
from sklearn import metrics
print(metrics.mean_squared_error(y_train, y_pred_train))
print(metrics.mean_squared_error(y_test, y_pred_test))

1.9051188707124018
10.402225480314959

In [52]:
new_data = rforest.predict(scaled_new_data)
new_data

array([28.68 , 40.762, 35.881])

In [53]:
y_pred

array([[23.824772],
       [31.382582],
       [31.826935]], dtype=float32)

In [55]:
dataset1['MEDV'].describe()

count    506.000000
mean      22.532806
std        9.197104
min        5.000000
25%       17.025000
50%       21.200000
75%       25.000000
max       50.000000
Name: MEDV, dtype: float64

In [59]:
# Linear regression
from sklearn.linear_model import LinearRegression
linear = LinearRegression()
linear.fit(x_train, y_train)
y_pred_test_linear = linear.predict(x_test)
y_pred_train_linear = linear.predict(x_train)
from sklearn import metrics
print(metrics.mean_squared_error(y_train, y_pred_train_linear))
print(metrics.mean_squared_error(y_test, y_pred_test_linear))

22.444153693670106
22.317355620262553

In [60]:
new_data_linear = linear.predict(scaled_new_data)
new_data_linear

array([27.8523542 , 27.51516573, 28.69122724])

In [61]:
print("Linear result")
print(new_data_linear)
print("RandomForest Result")
print(new_data)
print("MultiLayer perceptron")
print(y_pred)

Linear result
[27.8523542  27.51516573 28.69122724]
RandomForest Result
[28.68  40.762 35.881]
MultiLayer perceptron
[[23.824772]
 [31.382582]
 [31.826935]]

In [62]:
history = model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=500, batch_size=32)

Epoch 1/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.8335 - val_loss: 13.9015
Epoch 2/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.0139 - val_loss: 13.8290
Epoch 3/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 13.3809 - val_loss: 13.7201
Epoch 4/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.0729 - val_loss: 13.7035
Epoch 5/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.2264 - val_loss: 13.6095
Epoch 6/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 10.1185 - val_loss: 13.6228
Epoch 7/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.7805 - val_loss: 13.6177
Epoch 8/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.9838 - val_loss: 13.5471
Epoch 9/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0965 - val_loss: 13.5511
Epoch 10/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.8789 - val_loss: 13.4672
Epoch 11/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.5799 - val_loss: 13.3712
Epoch 12/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.0183 - val_loss: 13.3324
Epoch 13/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.1344 - val_loss: 13.3476
Epoch 14/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.8543 - val_loss: 13.3057
Epoch 15/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3266 - val_loss: 13.3097
Epoch 16/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.5711 - val_loss: 13.2190
Epoch 17/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.9847 - val_loss: 13.1248
Epoch 18/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8652 - val_loss: 13.2286
Epoch 19/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.5203 - val_loss: 13.1433
Epoch 20/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1467 - val_loss: 13.1598
Epoch 21/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.4277 - val_loss: 13.0960
Epoch 22/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6591 - val_loss: 13.1450
Epoch 23/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.4875 - val_loss: 13.0146
Epoch 24/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.6492 - val_loss: 13.0345
Epoch 25/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.2703 - val_loss: 13.0102
Epoch 26/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3068 - val_loss: 13.0026
Epoch 27/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4508 - val_loss: 12.9151
Epoch 28/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5064 - val_loss: 12.9303
Epoch 29/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.1078 - val_loss: 12.8809
Epoch 30/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 11.0471 - val_loss: 12.8985
Epoch 31/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.7563 - val_loss: 12.8645
Epoch 32/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9810 - val_loss: 12.8829
Epoch 33/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4564 - val_loss: 12.8196
Epoch 34/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.5552 - val_loss: 12.7888
Epoch 35/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6359 - val_loss: 12.7857
Epoch 36/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.7966 - val_loss: 12.7606
Epoch 37/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.1152 - val_loss: 12.6990
Epoch 38/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.7306 - val_loss: 12.6626
Epoch 39/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9.3667 - val_loss: 12.7248
Epoch 40/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.8862 - val_loss: 12.6149
Epoch 41/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.9969 - val_loss: 12.6745
Epoch 42/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.4681 - val_loss: 12.5958
Epoch 43/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.7508 - val_loss: 12.7035
Epoch 44/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.1901 - val_loss: 12.5876
Epoch 45/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7941 - val_loss: 12.5902
Epoch 46/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.7143 - val_loss: 12.5848
Epoch 47/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.6907 - val_loss: 12.6144
Epoch 48/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.6789 - val_loss: 12.6435
Epoch 49/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.6022 - val_loss: 12.6480
Epoch 50/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.7147 - val_loss: 12.4996
Epoch 51/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.6618 - val_loss: 12.5603
Epoch 52/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.3661 - val_loss: 12.6041
Epoch 53/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9889 - val_loss: 12.5960
Epoch 54/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8104 - val_loss: 12.5009
Epoch 55/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5205 - val_loss: 12.5064
Epoch 56/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3954 - val_loss: 12.6570
Epoch 57/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.2197 - val_loss: 12.4961
Epoch 58/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.1905 - val_loss: 12.5573
Epoch 59/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5318 - val_loss: 12.4781
Epoch 60/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5397 - val_loss: 12.4065
Epoch 61/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.0889 - val_loss: 12.4668
Epoch 62/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.5353 - val_loss: 12.5131
Epoch 63/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.2578 - val_loss: 12.4974
Epoch 64/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.8685 - val_loss: 12.4901
Epoch 65/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3115 - val_loss: 12.4267
Epoch 66/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6528 - val_loss: 12.5200
Epoch 67/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9966 - val_loss: 12.4967
Epoch 68/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.8037 - val_loss: 12.6325
Epoch 69/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8763 - val_loss: 12.4473
Epoch 70/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.7710 - val_loss: 12.4946
Epoch 71/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4320 - val_loss: 12.5606
Epoch 72/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.3584 - val_loss: 12.5416
Epoch 73/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.9306 - val_loss: 12.4764
Epoch 74/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.8640 - val_loss: 12.5289
Epoch 75/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2483 - val_loss: 12.5174
Epoch 76/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.3447 - val_loss: 12.4780
Epoch 77/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.4076 - val_loss: 12.5835
Epoch 78/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.3074 - val_loss: 12.4696
Epoch 79/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.7709 - val_loss: 12.5356
Epoch 80/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.9486 - val_loss: 12.5197
Epoch 81/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.7147 - val_loss: 12.5729
Epoch 82/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.3537 - val_loss: 12.3440
Epoch 83/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.0888 - val_loss: 12.4647
Epoch 84/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4372 - val_loss: 12.4731
Epoch 85/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.9327 - val_loss: 12.3728
Epoch 86/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.4799 - val_loss: 12.5495
Epoch 87/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.8873 - val_loss: 12.3643
Epoch 88/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.5270 - val_loss: 12.3573
Epoch 89/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.2205 - val_loss: 12.5034
Epoch 90/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.7998 - val_loss: 12.4101
Epoch 91/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.5103 - val_loss: 12.3700
Epoch 92/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.8902 - val_loss: 12.4194
Epoch 93/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4139 - val_loss: 12.4612
Epoch 94/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5990 - val_loss: 12.3277
Epoch 95/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.5961 - val_loss: 12.3520
Epoch 96/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.5508 - val_loss: 12.4429
Epoch 97/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.1663 - val_loss: 12.3875
Epoch 98/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.6208 - val_loss: 12.3246
Epoch 99/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.0176 - val_loss: 12.4941
Epoch 100/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.1311 - val_loss: 12.3944
Epoch 101/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.2494 - val_loss: 12.3714
Epoch 102/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7.4417 - val_loss: 12.3426
Epoch 103/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6309 - val_loss: 12.7188
Epoch 104/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.3790 - val_loss: 12.2506
Epoch 105/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.6439 - val_loss: 12.3472
Epoch 106/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.1545 - val_loss: 12.4000
Epoch 107/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.5847 - val_loss: 12.3285
Epoch 108/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.3527 - val_loss: 12.4012
Epoch 109/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.4100 - val_loss: 12.3747
Epoch 110/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.8520 - val_loss: 12.3805
Epoch 111/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0313 - val_loss: 12.4720
Epoch 112/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.9806 - val_loss: 12.2812
Epoch 113/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.4798 - val_loss: 12.4930
Epoch 114/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.6109 - val_loss: 12.3713
Epoch 115/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.0901 - val_loss: 12.3205
Epoch 116/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 8.1421 - val_loss: 12.3640
Epoch 117/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.5657 - val_loss: 12.3838
Epoch 118/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.7874 - val_loss: 12.3175
Epoch 119/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.1809 - val_loss: 12.4051
Epoch 120/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.7116 - val_loss: 12.2593
Epoch 121/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.4316 - val_loss: 12.3855
Epoch 122/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.7433 - val_loss: 12.4645
Epoch 123/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.0342 - val_loss: 12.4293
Epoch 124/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.4499 - val_loss: 12.2843
Epoch 125/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.6419 - val_loss: 12.4179
Epoch 126/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.9405 - val_loss: 12.4401
Epoch 127/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0434 - val_loss: 12.4405
Epoch 128/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.3206 - val_loss: 12.4072
Epoch 129/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.4537 - val_loss: 12.2277
Epoch 130/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.9830 - val_loss: 12.4612
Epoch 131/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.0475 - val_loss: 12.4810
Epoch 132/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.3594 - val_loss: 12.3310
Epoch 133/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.1057 - val_loss: 12.4403
Epoch 134/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.4300 - val_loss: 12.3846
Epoch 135/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.8296 - val_loss: 12.3751
Epoch 136/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7.6304 - val_loss: 12.3887
Epoch 137/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.0558 - val_loss: 12.4319
Epoch 138/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.4019 - val_loss: 12.4650
Epoch 139/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.3599 - val_loss: 12.2700
Epoch 140/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.4247 - val_loss: 12.4470
Epoch 141/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.5941 - val_loss: 12.4115
Epoch 142/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.4116 - val_loss: 12.2933
Epoch 143/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.4089 - val_loss: 12.3641
Epoch 144/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.0750 - val_loss: 12.2016
Epoch 145/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.8938 - val_loss: 12.4422
Epoch 146/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.3556 - val_loss: 12.3949
Epoch 147/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.4336 - val_loss: 12.2973
Epoch 148/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.2829 - val_loss: 12.3553
Epoch 149/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.8854 - val_loss: 12.4457
Epoch 150/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.1822 - val_loss: 12.3015
Epoch 151/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.8999 - val_loss: 12.2920
Epoch 152/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.5494 - val_loss: 12.2897
Epoch 153/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.6173 - val_loss: 12.4249
Epoch 154/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.4608 - val_loss: 12.2532
Epoch 155/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.0655 - val_loss: 12.4119
Epoch 156/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.6966 - val_loss: 12.3835
Epoch 157/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.1531 - val_loss: 12.2133
Epoch 158/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.3608 - val_loss: 12.2726
Epoch 159/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.3099 - val_loss: 12.4393
Epoch 160/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.2270 - val_loss: 12.3136
Epoch 161/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.9056 - val_loss: 12.2227
Epoch 162/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.0468 - val_loss: 12.3665
Epoch 163/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.9417 - val_loss: 12.3374
Epoch 164/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.2744 - val_loss: 12.2289
Epoch 165/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.8824 - val_loss: 12.4462
Epoch 166/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.7802 - val_loss: 12.3770
Epoch 167/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.9515 - val_loss: 12.2325
Epoch 168/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.3916 - val_loss: 12.2918
Epoch 169/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.5781 - val_loss: 12.1935
Epoch 170/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.2367 - val_loss: 12.2564
Epoch 171/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.0994 - val_loss: 12.3514
Epoch 172/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.9454 - val_loss: 12.1279
Epoch 173/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.1391 - val_loss: 12.2602
Epoch 174/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.9219 - val_loss: 12.4398
Epoch 175/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.0879 - val_loss: 12.2842
Epoch 176/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.5490 - val_loss: 12.1505
Epoch 177/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.7526 - val_loss: 12.4166
Epoch 178/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 5.1700 - val_loss: 12.1121
Epoch 179/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.4593 - val_loss: 12.2640
Epoch 180/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.9189 - val_loss: 12.2051
Epoch 181/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.1612 - val_loss: 12.1944
Epoch 182/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.4442 - val_loss: 12.2279
Epoch 183/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.1358 - val_loss: 12.1523
Epoch 184/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.9859 - val_loss: 12.1147
Epoch 185/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.1848 - val_loss: 12.3093
Epoch 186/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.4667 - val_loss: 12.0666
Epoch 187/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.2993 - val_loss: 12.0958
Epoch 188/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.2255 - val_loss: 12.3782
Epoch 189/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.4057 - val_loss: 12.1056
Epoch 190/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.9891 - val_loss: 12.2715
Epoch 191/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.8330 - val_loss: 12.2332
Epoch 192/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.1425 - val_loss: 12.1111
Epoch 193/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.3306 - val_loss: 12.1756
Epoch 194/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.6405 - val_loss: 12.1594
Epoch 195/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.3176 - val_loss: 12.1802
Epoch 196/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.7899 - val_loss: 12.1780
Epoch 197/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.9585 - val_loss: 11.9764
Epoch 198/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.0562 - val_loss: 12.3765
Epoch 199/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.0412 - val_loss: 12.1158
Epoch 200/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.6039 - val_loss: 12.1662
Epoch 201/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.1812 - val_loss: 12.1320
Epoch 202/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.7810 - val_loss: 12.1278
Epoch 203/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.2043 - val_loss: 12.0355
Epoch 204/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.8158 - val_loss: 12.1897
Epoch 205/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.9295 - val_loss: 12.0275
Epoch 206/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.9221 - val_loss: 12.2067
Epoch 207/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.1687 - val_loss: 12.0925
Epoch 208/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.0356 - val_loss: 12.0541
Epoch 209/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.7367 - val_loss: 11.9549
Epoch 210/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.4358 - val_loss: 12.0425
Epoch 211/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.5544 - val_loss: 12.0819
Epoch 212/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.4104 - val_loss: 12.1012
Epoch 213/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.5741 - val_loss: 11.9832
Epoch 214/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.4052 - val_loss: 12.0608
Epoch 215/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.7054 - val_loss: 11.8949
Epoch 216/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.2636 - val_loss: 12.2869
Epoch 217/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.1080 - val_loss: 11.7911
Epoch 218/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.7260 - val_loss: 12.0229
Epoch 219/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.6603 - val_loss: 11.8586
Epoch 220/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.4649 - val_loss: 12.0888
Epoch 221/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.7950 - val_loss: 11.9725
Epoch 222/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 4.3451 - val_loss: 12.0389
Epoch 223/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.8849 - val_loss: 11.9572
Epoch 224/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.0464 - val_loss: 11.8924
Epoch 225/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.0018 - val_loss: 11.9795
Epoch 226/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.5100 - val_loss: 12.0046
Epoch 227/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.3496 - val_loss: 12.0081
Epoch 228/500
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.6654 - val_loss: 11.9799
Epoch 229/500

In [63]:
history = model.fit(x_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2.5582
Epoch 2/10
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.7966
Epoch 3/10
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3.2872
Epoch 4/10
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.0506
Epoch 5/10
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.8385
Epoch 6/10
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.7955
Epoch 7/10
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.1959
Epoch 8/10
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.4366
Epoch 9/10
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.7590
Epoch 10/10
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.6081

In [ ]:
model.fit(x_test, y_test, epochs=10, batch_size=32)